// COURSE ANNOUNCEMENTS FETCH
export const ANNOUNCEMENTS_FETCH_STARTED = 'ANNOUNCEMENTS_FETCH_STARTED';
export const ANNOUNCEMENTS_FETCH_COMPLETED = 'ANNOUNCEMENTS_FETCH_COMPLETED';
export const ANNOUNCEMENTS_FETCH_FAILED = 'ANNOUNCEMENTS_FETCH_FAILED';

// ANNOUNCEMENT FETCH
export const ANNOUNCEMENT_FETCH_STARTED = 'ANNOUNCEMENT_FETCH_STARTED';
export const ANNOUNCEMENT_FETCH_COMPLETED = 'ANNOUNCEMENT_FETCH_COMPLETED';
export const ANNOUNCEMENT_FETCH_FAILED = 'ANNOUNCEMENT_FETCH_FAILED';

// COURSE ANNOUNCEMENT ADD
export const ANNOUNCEMENT_ADD_STARTED = 'ANNOUNCEMENTS_ADD_STARTED';
export const ANNOUNCEMENT_ADD_COMPLETED = 'ANNOUNCEMENTS_ADD_COMPLETED';
export const ANNOUNCEMENT_ADD_FAILED = 'ANNOUNCEMENTS_ADD_FAILED';

// COURSE ANNOUNCEMENT REMOVE 
export const ANNOUNCEMENT_REMOVE_STARTED = 'ANNOUNCEMENTS_REMOVE_STARTED';
export const ANNOUNCEMENT_REMOVE_COMPLETED = 'ANNOUNCEMENTS_REMOVE_COMPLETED';
export const ANNOUNCEMENT_REMOVE_FAILED = 'ANNOUNCEMENTS_REMOVE_FAILED';
