// ASSIGNMENTS FETCH
export const ASSIGNMENTS_FETCH_STARTED = 'ASSIGNMENTS_FETCH_STARTED';
export const ASSIGNMENTS_FETCH_COMPLETED = 'ASSIGNMENTS_FETCH_COMPLETED';
export const ASSIGNMENTS_FETCH_FAILED = 'ASSIGNMENTS_FETCH_FAILED';

// ASSIGNMENT FETCH
export const ASSIGNMENT_FETCH_STARTED = 'ASSIGNMENT_FETCH_STARTED';
export const ASSIGNMENT_FETCH_COMPLETED = 'ASSIGNMENT_FETCH_COMPLETED';
export const ASSIGNMENT_FETCH_FAILED = 'ASSIGNMENT_FETCH_FAILED';

// ASSIGNMENT SCORE
export const ASSIGNMENT_SCORE_STARTED = 'ASSIGNMENT_SCORE_STARTED';
export const ASSIGNMENT_SCORE_COMPLETED = 'ASSIGNMENT_SCORE_COMPLETED';
export const ASSIGNMENT_SCORE_FAILED = 'ASSIGNMENT_SCORE_FAILED';

// ASSIGNMENT SUBMIT
export const ASSIGNMENT_SUBMIT_STARTED = 'ASSIGNMENT_SUBMIT_STARTED';
export const ASSIGNMENT_SUBMIT_COMPLETED = 'ASSIGNMENT_SUBMIT_COMPLETED';
export const ASSIGNMENT_SUBMIT_FAILED = 'ASSIGNMENT_SUBMIT_FAILED';

// ASSIGNMENT EDIT
export const ASSIGNMENT_EDIT_STARTED = 'ASSIGNMENT_EDIT_STARTED';
export const ASSIGNMENT_EDIT_COMPLETED = 'ASSIGNMENT_EDIT_COMPLETED';
export const ASSIGNMENT_EDIT_FAILED = 'ASSIGNMENT_EDIT_FAILED';

// COURSE ASSIGNMENTS FETCH
export const COURSE_ASSIGNMENTS_FETCH_STARTED = 'COURSE_ASSIGNMENTS_FETCH_STARTED';
export const COURSE_ASSIGNMENTS_FETCH_COMPLETED = 'COURSE_ASSIGNMENTS_FETCH_COMPLETED';
export const COURSE_ASSIGNMENTS_FETCH_FAILED = 'COURSE_ASSIGNMENTS_FETCH_FAILED';

// COURSE ASSIGNMENT EDIT
export const COURSE_ASSIGNMENT_EDIT_STARTED = 'COURSE_ASSIGNMENT_EDIT_STARTED';
export const COURSE_ASSIGNMENT_EDIT_COMPLETED = 'COURSE_ASSIGNMENT_EDIT_COMPLETED';
export const COURSE_ASSIGNMENT_EDIT_FAILED = 'COURSE_ASSIGNMENT_EDIT_FAILED';

// COURSE ASSIGNMENT ADD
export const COURSE_ASSIGNMENT_ADD_STARTED = 'COURSE_ASSIGNMENT_ADD_STARTED';
export const COURSE_ASSIGNMENT_ADD_COMPLETED = 'COURSE_ASSIGNMENT_ADD_COMPLETED';
export const COURSE_ASSIGNMENT_ADD_FAILED = 'COURSE_ASSIGNMENT_ADD_FAILED';

// COURSE ASSIGNMENT REMOVE
export const COURSE_ASSIGNMENT_REMOVE_STARTED = 'COURSE_ASSIGNMENT_REMOVE_STARTED';
export const COURSE_ASSIGNMENT_REMOVE_COMPLETED = 'COURSE_ASSIGNMENT_REMOVE_COMPLETED';
export const COURSE_ASSIGNMENT_REMOVE_FAILED = 'COURSE_ASSIGNMENT_REMOVE_FAILED';