export const ASSIGNMENT_FETCH_STARTED = 'ASSIGNMENT_FETCH_STARTED';
export const ASSIGNMENT_FETCH_COMPLETED = 'ASSIGNMENT_FETCH_COMPLETED';
export const ASSIGNMENT_FETCH_FAILED = 'ASSIGNMENT_FETCH_FAILED';

export const ASSIGNMENT_ADD_STARTED = 'ASSIGNMENT_ADD_STARTED';
export const ASSIGNMENT_ADD_COMPLETED = 'ASSIGNMENT_ADD_COMPLETED';
export const ASSIGNMENT_ADD_FAILED = 'ASSIGNMENT_ADD_FAILED';

export const ASSIGNMENT_REMOVE_STARTED = 'ASSIGNMENT_REMOVE_STARTED';
export const ASSIGNMENT_REMOVE_COMPLETED = 'ASSIGNMENT_REMOVE_COMPLETED';
export const ASSIGNMENT_REMOVE_FAILED = 'ASSIGNMENT_REMOVE_FAILED';

export const ASSIGNMENT_SCORE_STARTED = 'ASSIGNMENT_SCORE_STARTED';
export const ASSIGNMENT_SCORE_COMPLETED = 'ASSIGNMENT_SCORE_COMPLETED';
export const ASSIGNMENT_SCORE_FAILED = 'ASSIGNMENT_SCORE_FAILED';

export const ASSIGNMENT_SUBMIT_STARTED = 'ASSIGNMENT_SUBMIT_STARTED';
export const ASSIGNMENT_SUBMIT_COMPLETED = 'ASSIGNMENT_SUBMIT_COMPLETED';
export const ASSIGNMENT_SUBMIT_FAILED = 'ASSIGNMENT_SUBMIT_FAILED';

export const ASSIGNMENT_EDIT_STARTED = 'ASSIGNMENT_EDIT_STARTED';
export const ASSIGNMENT_EDIT_COMPLETED = 'ASSIGNMENT_EDIT_COMPLETED';
export const ASSIGNMENT_EDIT_FAILED = 'ASSIGNMENT_EDIT_FAILED';
