export const COURSES_FETCH_STARTED = 'COURSES_FETCH_STARTED';
export const COURSES_FETCH_COMPLETED = 'COURSES_FETCH_COMPLETED';
export const COURSES_FETCH_FAILED = 'COURSES_FETCH_FAILED';

export const COURSE_FETCH_STARTED = 'COURSE_FETCH_STARTED';
export const COURSE_FETCH_COMPLETED = 'COURSE_FETCH_COMPLETED';
export const COURSE_FETCH_FAILED = 'COURSE_FETCH_FAILED';

export const COURSE_ADD_STARTED = 'COURSE_ADD_STARTED';
export const COURSE_ADD_COMPLETED = 'COURSE_ADD_COMPLETED';
export const COURSE_ADD_FAILED = 'COURSE_ADD_FAILED';

export const COURSE_REMOVE_STARTED = 'COURSE_REMOVE_STARTED';
export const COURSE_REMOVE_COMPLETED = 'COURSE_REMOVE_COMPLETED';
export const COURSE_REMOVE_FAILED = 'COURSE_REMOVE_FAILED';

export const COURSE_EDIT_STARTED = 'COURSE_EDIT_STARTED';
export const COURSE_EDIT_COMPLETED = 'COURSE_EDIT_COMPLETED';
export const COURSE_EDIT_FAILED = 'COURSE_EDIT_FAILED';