export const ESTABLISHMENT_FETCH_STARTED = 'ESTABLISHMENT_FETCH_STARTED';
export const ESTABLISHMENT_FETCH_COMPLETED = 'ESTABLISHMENT_FETCH_COMPLETED';
export const ESTABLISHMENT_FETCH_FAILED = 'ESTABLISHMENT_FETCH_FAILED';