// GROUPS FETCH
export const GROUPS_FETCH_STARTED = 'GROUPS_FETCH_STARTED';
export const GROUPS_FETCH_COMPLETED = 'GROUPS_FETCH_COMPLETED';
export const GROUPS_FETCH_FAILED = 'GROUPS_FETCH_FAILED';

// GROUP FETCH
export const GROUP_FETCH_STARTED = 'GROUP_FETCH_STARTED';
export const GROUP_FETCH_COMPLETED = 'GROUP_FETCH_COMPLETED';
export const GROUP_FETCH_FAILED = 'GROUP_FETCH_FAILED';

// GROUP EDIT
export const GROUP_EDIT_STARTED = 'GROUP_EDIT_STARTED';
export const GROUP_EDIT_COMPLETED = 'GROUP_EDIT_COMPLETED';
export const GROUP_EDIT_FAILED = 'GROUP_EDIT_FAILED';

// GROUP REMOVE
export const GROUP_REMOVE_STARTED = 'GROUP_REMOVE_STARTED';
export const GROUP_REMOVE_COMPLETED = 'GROUP_REMOVE_COMPLETED';
export const GROUP_REMOVE_FAILED = 'GROUP_REMOVE_FAILED';

// COURSE GROUPS FETCH
export const COURSE_GROUPS_FETCH_STARTED = 'COURSE_GROUPS_FETCH_STARTED';
export const COURSE_GROUPS_FETCH_COMPLETED = 'COURSE_GROUPS_FETCH_COMPLETED';
export const COURSE_GROUPS_FETCH_FAILED = 'COURSE_GROUPS_FETCH_FAILED';

// COURSE GROUPS FETCH
export const COURSE_GROUP_ADD_STARTED = 'COURSE_GROUP_ADD_STARTED';
export const COURSE_GROUP_ADD_COMPLETED = 'COURSE_GROUP_ADD_COMPLETED';
export const COURSE_GROUP_ADD_FAILED = 'COURSE_GROUPS_ADD_FAILED';