export const PROFESSOR_COURSES_FETCH_STARTED = 'PROFESSOR_COURSES_FETCH_STARTED';
export const PROFESSOR_COURSES_FETCH_COMPLETED = 'PROFESSOR_COURSES_FETCH_COMPLETED';
export const PROFESSOR_COURSES_FETCH_FAILED = 'PROFESSOR_COURSES_FETCH_FAILED';

export const PROFESSOR_COURSE_ADD_STARTED = 'PROFESSOR_COURSE_ADD_STARTED';
export const PROFESSOR_COURSE_ADD_COMPLETED = 'PROFESSOR_COURSE_ADD_COMPLETED';
export const PROFESSOR_COURSE_ADD_FAILED = 'PROFESSOR_COURSE_ADD_FAILED';

export const PROFESSOR_COURSE_REMOVE_STARTED = 'PROFESSOR_COURSE_REMOVE_STARTED';
export const PROFESSOR_COURSE_REMOVE_COMPLETED = 'PROFESSOR_COURSE_REMOVE_COMPLETED';
export const PROFESSOR_COURSE_REMOVE_FAILED = 'PROFESSOR_COURSE_REMOVE_FAILED';

export const PROFESSOR_COURSE_EDIT_STARTED = 'PROFESSOR_COURSE_EDIT_STARTED';
export const PROFESSOR_COURSE_EDIT_COMPLETED = 'PROFESSOR_COURSE_EDIT_COMPLETED';
export const PROFESSOR_COURSE_EDIT_FAILED = 'PROFESSOR_COURSE_EDIT_FAILED';