export const STUDENT_COURSES_FETCH_STARTED = 'STUDENT_COURSES_FETCH_STARTED';
export const STUDENT_COURSES_FETCH_COMPLETED = 'STUDENT_COURSES_FETCH_COMPLETED';
export const STUDENT_COURSES_FETCH_FAILED = 'STUDENT_COURSES_FETCH_FAILED';

export const STUDENT_COURSE_ADD_STARTED = 'STUDENT_COURSE_ADD_STARTED';
export const STUDENT_COURSE_ADD_COMPLETED = 'STUDENT_COURSE_ADD_COMPLETED';
export const STUDENT_COURSE_ADD_FAILED = 'STUDENT_COURSE_ADD_FAILED';

export const STUDENT_COURSE_REMOVE_STARTED = 'STUDENT_COURSE_REMOVE_STARTED';
export const STUDENT_COURSE_REMOVE_COMPLETED = 'STUDENT_COURSE_REMOVE_COMPLETED';
export const STUDENT_COURSE_REMOVE_FAILED = 'STUDENT_COURSE_REMOVE_FAILED';

export const STUDENT_COURSE_EDIT_STARTED = 'STUDENT_COURSE_EDIT_STARTED';
export const STUDENT_COURSE_EDIT_COMPLETED = 'STUDENT_COURSE_EDIT_COMPLETED';
export const STUDENT_COURSE_EDIT_FAILED = 'STUDENT_COURSE_EDIT_FAILED';